-- MySQL Script generated by MySQL Workbench
-- 04/04/17 23:42:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema twitterfy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `twitterfy` ;

-- -----------------------------------------------------
-- Schema twitterfy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `twitterfy` DEFAULT CHARACTER SET utf8mb4 ;
USE `twitterfy` ;

-- -----------------------------------------------------
-- Table `twitterfy`.`Tweet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twitterfy`.`Tweet` ;

CREATE TABLE IF NOT EXISTS `twitterfy`.`Tweet` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tweet` VARCHAR(254) CHARACTER SET 'utf8mb4' NOT NULL,
  `processed` TINYINT(1) NULL DEFAULT 0,
  `screenName` VARCHAR(254) CHARACTER SET 'utf8mb4' NOT NULL,
  `timestamp` BIGINT NOT NULL,
  `timestampStr` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
